/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExceptionBase: typeof import('./src/components/exception-base.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NWatermark: typeof import('naive-ui')['NWatermark']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ExceptionBase: typeof import('./src/components/exception-base.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NInput: typeof import('naive-ui')['NInput']
  const NTabPane: typeof import('naive-ui')['NTabPane']
  const NTabs: typeof import('naive-ui')['NTabs']
  const NTooltip: typeof import('naive-ui')['NTooltip']
  const NWatermark: typeof import('naive-ui')['NWatermark']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}